<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="EmpJob">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" name="EmpJob">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element nillable="false" maxOccurs="1" name="payScaleType">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="128"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element type="xs:dateTime" nillable="true" minOccurs="0" maxOccurs="1" name="positionEntryDate" xmlns=""/>
                            <xs:element nillable="false" maxOccurs="1" name="position">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="128"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element type="xs:dateTime" nillable="true" minOccurs="0" maxOccurs="1" name="probationPeriodEndDate" xmlns=""/>
                            <xs:element type="xs:long" nillable="false" maxOccurs="1" name="seqNumber" xmlns=""/>
                            <xs:element type="xs:dateTime" nillable="false" maxOccurs="1" name="startDate" xmlns=""/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
