<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="cust_subcapability">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="cust_subcapability" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:dateTime" name="lastModifiedDateTime"/>
							<xs:element type="xs:int" name="externalCode"/>
							<xs:element type="xs:string" name="externalName"/>
							<xs:element type="xs:dateTime" name="effectiveStartDate"/>
							<xs:element name="cust_capability">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="cust_capability">
											<xs:complexType>
												<xs:sequence>
													<xs:element type="xs:dateTime" name="lastModifiedDateTime"/>
													<xs:element type="xs:int" name="externalCode"/>
													<xs:element type="xs:string" name="externalName"/>
													<xs:element type="xs:dateTime" name="effectiveStartDate"/>
													<xs:element name="cust_Memberfirmbusiness">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="FODivision">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element type="xs:string" name="name_defaultValue"/>
																			<xs:element type="xs:int" name="externalCode"/>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>