<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Row" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:choice maxOccurs="unbounded" minOccurs="0">
              <xs:element type="xs:dateTime" name="Industry_effectiveStartDate"/>
              <xs:element type="xs:string" name="Industry_externalCode"/>
              <xs:element type="xs:string" name="Industry_label_defaultValue"/>
              <xs:element type="xs:string" name="Industry_status"/>
              <xs:element type="xs:dateTime" name="Industry_lastModifiedDateTime"/>
              <xs:element type="xs:dateTime" name="Sector_effectiveStartDate"/>
              <xs:element type="xs:string" name="Sector_externalCode"/>
              <xs:element type="xs:string" name="Sector_label_defaultValue"/>
              <xs:element type="xs:string" name="Sector_status"/>
              <xs:element type="xs:dateTime" name="Sector_lastModifiedDateTime"/>			  
            </xs:choice>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>