<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="EmpEmployment">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" name="EmpEmployment">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element nillable="false" maxOccurs="1" name="personIdExternal">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element nillable="false" maxOccurs="1" name="userId">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element type="xs:dateTime" nillable="false" maxOccurs="1" name="endDate" xmlns=""/>
                            <xs:element type="xs:dateTime" nillable="true" minOccurs="0" maxOccurs="1" name="originalStartDate" xmlns=""/>
                            <xs:element type="xs:dateTime" nillable="false" maxOccurs="1" name="startDate" xmlns=""/>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="assignmentClass">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="128"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="assignmentIdExternal">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="256"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="compInfoNav">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element minOccurs="0" maxOccurs="unbounded" name="EmpCompensation">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:dateTime" nillable="false" maxOccurs="1" name="startDate" xmlns=""/>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="empPayCompRecurringNav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="unbounded" name="EmpPayCompRecurring">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="false" maxOccurs="1" name="payComponent">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="100"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element type="xs:double" nillable="false" maxOccurs="1" name="paycompvalue" xmlns=""/>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="empJobRelationshipNav">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element minOccurs="0" maxOccurs="unbounded" name="EmpJobRelationships">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element nillable="false" maxOccurs="1" name="relationshipType">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string" xmlns="">
                                                                <xs:maxLength value="100"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element nillable="false" maxOccurs="1" name="relUserId">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string" xmlns="">
                                                                <xs:maxLength value="384"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="relUserNav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="1" name="User">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="false" maxOccurs="1" name="userId">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="100"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="relationshipTypeNav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="1" name="PicklistOption">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="externalCode">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="256"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="relEmploymentNav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="1" name="EmpEmployment">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="personNav">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element minOccurs="0" maxOccurs="1" name="PerPerson">
                                                                                            <xs:complexType>
                                                                                                <xs:sequence>
                                                                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="personalInfoNav">
                                                                                                        <xs:complexType>
                                                                                                            <xs:sequence>
                                                                                                                <xs:element minOccurs="0" maxOccurs="unbounded" name="PerPersonal">
                                                                                                                    <xs:complexType>
                                                                                                                        <xs:sequence>
                                                                                                                            <xs:element nillable="false" maxOccurs="1" name="firstName">
                                                                                                                                <xs:simpleType>
                                                                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                                                                        <xs:maxLength value="40"/>
                                                                                                                                    </xs:restriction>
                                                                                                                                </xs:simpleType>
                                                                                                                            </xs:element>
                                                                                                                            <xs:element nillable="false" maxOccurs="1" name="lastName">
                                                                                                                                <xs:simpleType>
                                                                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                                                                        <xs:maxLength value="40"/>
                                                                                                                                    </xs:restriction>
                                                                                                                                </xs:simpleType>
                                                                                                                            </xs:element>
                                                                                                                        </xs:sequence>
                                                                                                                    </xs:complexType>
                                                                                                                </xs:element>
                                                                                                            </xs:sequence>
                                                                                                        </xs:complexType>
                                                                                                    </xs:element>
                                                                                                </xs:sequence>
                                                                                            </xs:complexType>
                                                                                        </xs:element>
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="assignmentIdExternal">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="256"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="paymentInformationNav">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element minOccurs="0" maxOccurs="unbounded" name="PaymentInformationV3">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="toPaymentInformationDetailV3">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="unbounded" name="PaymentInformationDetailV3">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="bank">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="128"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="bankNav">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element minOccurs="0" maxOccurs="1" name="Bank">
                                                                                            <xs:complexType>
                                                                                                <xs:sequence>
                                                                                                    <xs:element nillable="false" maxOccurs="1" name="bankName">
                                                                                                        <xs:simpleType>
                                                                                                            <xs:restriction base="xs:string" xmlns="">
                                                                                                                <xs:maxLength value="128"/>
                                                                                                            </xs:restriction>
                                                                                                        </xs:simpleType>
                                                                                                    </xs:element>
                                                                                                </xs:sequence>
                                                                                            </xs:complexType>
                                                                                        </xs:element>
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="accountNumber">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="255"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="accountOwner">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="40"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="iban">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="35"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="jobInfoNav">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element minOccurs="0" maxOccurs="unbounded" name="EmpJob">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="emplStatusNav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="1" name="PicklistOption">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="externalCode">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="256"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="companyNav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="1" name="FOCompany">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="false" maxOccurs="1" name="externalCode">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="4"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="name_defaultValue">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="90"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="jobTitle">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string" xmlns="">
                                                                <xs:maxLength value="256"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element nillable="false" maxOccurs="1" name="company">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string" xmlns="">
                                                                <xs:maxLength value="4"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="employeeClassNav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="1" name="PicklistOption">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="externalCode">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="256"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element type="xs:string" nillable="true" minOccurs="0" maxOccurs="1" name="localeLabel" xmlns=""/>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="mdfExternalCode">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="256"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="eventReasonNav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="1" name="FOEventReason">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="emplStatusNav">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element minOccurs="0" maxOccurs="1" name="PicklistOption">
                                                                                            <xs:complexType>
                                                                                                <xs:sequence>
                                                                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="externalCode">
                                                                                                        <xs:simpleType>
                                                                                                            <xs:restriction base="xs:string" xmlns="">
                                                                                                                <xs:maxLength value="256"/>
                                                                                                            </xs:restriction>
                                                                                                        </xs:simpleType>
                                                                                                    </xs:element>
                                                                                                </xs:sequence>
                                                                                            </xs:complexType>
                                                                                        </xs:element>
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                            <xs:element nillable="false" maxOccurs="1" name="externalCode">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="32"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="name">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="32"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="emplStatus">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string" xmlns="">
                                                                <xs:maxLength value="32"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element type="xs:dateTime" nillable="false" maxOccurs="1" name="startDate" xmlns=""/>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="positionNav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="1" name="Position">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="false" maxOccurs="1" name="code">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="128"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="externalName_defaultValue">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="255"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="customString25Nav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="1" name="cust_PersonnelSubArea">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="false" maxOccurs="1" name="personnelSubAreaName">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="128"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="customString25">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string" xmlns="">
                                                                <xs:maxLength value="128"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="customString29Nav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="1" name="PicklistOption">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="externalCode">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="256"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element type="xs:string" nillable="true" minOccurs="0" maxOccurs="1" name="localeLabel" xmlns=""/>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="mdfExternalCode">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="256"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="costCenterNav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="1" name="FOCostCenter">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="false" maxOccurs="1" name="externalCode">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="14"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="description_defaultValue">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="128"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="description">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="128"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="name_defaultValue">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="90"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="workscheduleCodeNav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="1" name="WorkSchedule">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="false" maxOccurs="1" name="externalCode">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="128"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element type="xs:dateTime" nillable="false" maxOccurs="1" name="startingDate" xmlns=""/>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="externalName_defaultValue">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="255"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element type="xs:decimal" nillable="true" minOccurs="0" maxOccurs="1" name="averageHoursPerMonth" xmlns=""/>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element type="xs:double" nillable="true" minOccurs="0" maxOccurs="1" name="standardHours" xmlns=""/>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="eventNav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="1" name="PicklistOption">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="externalCode">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="256"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element type="xs:string" nillable="true" minOccurs="0" maxOccurs="1" name="localeLabel" xmlns=""/>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="contractTypeNav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="1" name="PicklistOption">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="externalCode">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="256"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element type="xs:string" nillable="true" minOccurs="0" maxOccurs="1" name="localeLabel" xmlns=""/>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element type="xs:dateTime" nillable="true" minOccurs="0" maxOccurs="1" name="probationPeriodEndDate" xmlns=""/>
                                                    <xs:element nillable="false" maxOccurs="1" name="payScaleArea">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string" xmlns="">
                                                                <xs:maxLength value="128"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element nillable="false" maxOccurs="1" name="payScaleGroup">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string" xmlns="">
                                                                <xs:maxLength value="128"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="payScaleLevel">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string" xmlns="">
                                                                <xs:maxLength value="128"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="customString24Nav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="1" name="cust_PersonnelArea">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="false" maxOccurs="1" name="personnelAreaCode">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="4"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="false" maxOccurs="1" name="personnelAreaName">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="30"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="customString66Nav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="1" name="FOCostCenter">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="false" maxOccurs="1" name="externalCode">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="14"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="customString24">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string" xmlns="">
                                                                <xs:maxLength value="4"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element type="xs:double" nillable="false" maxOccurs="1" name="customDouble1" xmlns=""/>
                                                    <xs:element type="xs:string" nillable="true" minOccurs="0" maxOccurs="1" name="countryOfCompany" xmlns=""/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="personNav">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element minOccurs="0" maxOccurs="1" name="PerPerson">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="personalInfoNav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="unbounded" name="PerPersonal">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="false" maxOccurs="1" name="firstName">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="40"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="formalName">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="80"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="false" maxOccurs="1" name="lastName">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="40"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="middleName">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="40"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="salutation">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="128"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="nativePreferredLangNav">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element minOccurs="0" maxOccurs="1" name="PicklistOption">
                                                                                            <xs:complexType>
                                                                                                <xs:sequence>
                                                                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="externalCode">
                                                                                                        <xs:simpleType>
                                                                                                            <xs:restriction base="xs:string" xmlns="">
                                                                                                                <xs:maxLength value="256"/>
                                                                                                            </xs:restriction>
                                                                                                        </xs:simpleType>
                                                                                                    </xs:element>
                                                                                                </xs:sequence>
                                                                                            </xs:complexType>
                                                                                        </xs:element>
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="maritalStatusNav">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element minOccurs="0" maxOccurs="1" name="PicklistOption">
                                                                                            <xs:complexType>
                                                                                                <xs:sequence>
                                                                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="externalCode">
                                                                                                        <xs:simpleType>
                                                                                                            <xs:restriction base="xs:string" xmlns="">
                                                                                                                <xs:maxLength value="256"/>
                                                                                                            </xs:restriction>
                                                                                                        </xs:simpleType>
                                                                                                    </xs:element>
                                                                                                    <xs:element type="xs:string" nillable="true" minOccurs="0" maxOccurs="1" name="localeLabel" xmlns=""/>
                                                                                                </xs:sequence>
                                                                                            </xs:complexType>
                                                                                        </xs:element>
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="nationality">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="128"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="gender">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="2"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="salutationNav">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element minOccurs="0" maxOccurs="1" name="PicklistOption">
                                                                                            <xs:complexType>
                                                                                                <xs:sequence>
                                                                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="externalCode">
                                                                                                        <xs:simpleType>
                                                                                                            <xs:restriction base="xs:string" xmlns="">
                                                                                                                <xs:maxLength value="256"/>
                                                                                                            </xs:restriction>
                                                                                                        </xs:simpleType>
                                                                                                    </xs:element>
                                                                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="mdfExternalCode">
                                                                                                        <xs:simpleType>
                                                                                                            <xs:restriction base="xs:string" xmlns="">
                                                                                                                <xs:maxLength value="256"/>
                                                                                                            </xs:restriction>
                                                                                                        </xs:simpleType>
                                                                                                    </xs:element>
                                                                                                </xs:sequence>
                                                                                            </xs:complexType>
                                                                                        </xs:element>
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element type="xs:dateTime" nillable="true" minOccurs="0" maxOccurs="1" name="dateOfBirth" xmlns=""/>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="nationalIdNav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="unbounded" name="PerNationalId">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="false" maxOccurs="1" name="cardType">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="256"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="false" maxOccurs="1" name="nationalId">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="256"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="emailNav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="unbounded" name="PerEmail">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="false" maxOccurs="1" name="emailType">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="38"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="false" maxOccurs="1" name="emailAddress">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="100"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="emailTypeNav">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element minOccurs="0" maxOccurs="1" name="PicklistOption">
                                                                                            <xs:complexType>
                                                                                                <xs:sequence>
                                                                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="externalCode">
                                                                                                        <xs:simpleType>
                                                                                                            <xs:restriction base="xs:string" xmlns="">
                                                                                                                <xs:maxLength value="256"/>
                                                                                                            </xs:restriction>
                                                                                                        </xs:simpleType>
                                                                                                    </xs:element>
                                                                                                </xs:sequence>
                                                                                            </xs:complexType>
                                                                                        </xs:element>
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="homeAddressNavDEFLT">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="unbounded" name="PerAddressDEFLT">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element type="xs:dateTime" nillable="false" maxOccurs="1" name="startDate" xmlns=""/>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="address1">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="256"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="address2">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="256"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="false" maxOccurs="1" name="address3">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="256"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="false" maxOccurs="1" name="city">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="256"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="false" maxOccurs="1" name="country">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="256"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="zipCode">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="256"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="false" maxOccurs="1" name="addressType">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="30"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="empGlobalAssignmentNav">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element minOccurs="0" maxOccurs="1" name="EmpGlobalAssignment">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:dateTime" nillable="false" maxOccurs="1" name="startDate" xmlns=""/>
                                                    <xs:element type="xs:dateTime" nillable="false" maxOccurs="1" name="plannedEndDate" xmlns=""/>
                                                    <xs:element type="xs:dateTime" nillable="false" maxOccurs="1" name="endDate" xmlns=""/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
