<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Record" maxOccurs="unbounded" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
            <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Employee_ID"/>
			<xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Legal_Name_English"/>
			<xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Legal_Name_Local"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Legal_Surname_English"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Legal_Surname_Local"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Cost_Center_Name"/>
	      <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Cost_Center_Percentage"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Cost_Center_Account_Number"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Cost_Center_Reserved_Field"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Employee_Birth_Date"/>
	      <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Marital_Status"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Gender"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Nationality"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Seniority_Date"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Hire_Date"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Military_Status"/>
	      <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Manager_Employee_ID"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Job_Or_Position_Title"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Social_Security_Job_Code"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Time_Type"/>
	      <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Local_Language_Job_Title"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Unit_ID"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Contract_Type"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Contract_End_Date"/>
	      <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="National_ID"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Passport_Reference_Number"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Phone_Number"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Employee_Email_Address"/>
	      <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Home_Address"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Bank_Account_Number"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Bank_Account_Holder_Name"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Bank_Name"/>
	      <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Social_Security_Reference_Number"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="IBAN_Number"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Education"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Disability_Level"/>
	      <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Dependents_Disability_Level_and_Rate"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Collective_Agreement"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Law_Number"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Document_type"/>
	      <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Disability_Status"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Retirement_Status"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Salary_Plan"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Amount"/>
	      <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Currency"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Salary_Period"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Gross_Or_Net"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Is_Rehire"/>
	      <xs:element type="xs:string" maxOccurs="1" minOccurs="1" name="Leave_Based_Entry_Date"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>