<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Record" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
            <xs:element type="xs:string" maxOccurs="1" minOccurs="0" name="Employee_ID"/>
			<xs:element type="xs:string" maxOccurs="1" minOccurs="0" name="Legal_Name_English"/>
			<xs:element type="xs:string" maxOccurs="1" minOccurs="0" name="Legal_Name_Local"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="0" name="Legal_Surname_English"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="0" name="Legal_Surname_Local"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="0" name="National_ID"/>
	      <xs:element type="xs:string" maxOccurs="1" minOccurs="0" name="Termination_Date"/>
              <xs:element type="xs:string" maxOccurs="1" minOccurs="0" name="Action_Reason"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>