<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="EmpEmployment">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" name="EmpEmployment">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="assignmentIdExternal">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="256"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element nillable="false" maxOccurs="1" name="personIdExternal">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="personNav">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element minOccurs="0" maxOccurs="1" name="PerPerson">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="personalInfoNav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="unbounded" name="PerPersonal">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="false" maxOccurs="1" name="firstName">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="40"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="firstNameAlt1">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="40"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="false" maxOccurs="1" name="lastName">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="40"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="lastNameAlt1">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="40"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="maritalStatusNav">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element minOccurs="0" maxOccurs="1" name="PicklistOption">
                                                                                            <xs:complexType>
                                                                                                <xs:sequence>
                                                                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="externalCode">
                                                                                                        <xs:simpleType>
                                                                                                            <xs:restriction base="xs:string" xmlns="">
                                                                                                                <xs:maxLength value="256"/>
                                                                                                            </xs:restriction>
                                                                                                        </xs:simpleType>
                                                                                                    </xs:element>
                                                                                                </xs:sequence>
                                                                                            </xs:complexType>
                                                                                        </xs:element>
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="gender">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="2"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="nationality">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="128"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element type="xs:dateTime" nillable="false" maxOccurs="1" name="startDate" xmlns=""/>
                                                                            <xs:element type="xs:dateTime" nillable="true" minOccurs="0" maxOccurs="1" name="lastModifiedDateTime" xmlns=""/>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element type="xs:dateTime" nillable="true" minOccurs="0" maxOccurs="1" name="dateOfBirth" xmlns=""/>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="nationalIdNav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="unbounded" name="PerNationalId">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="false" maxOccurs="1" name="nationalId">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="256"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element type="xs:dateTime" nillable="true" minOccurs="0" maxOccurs="1" name="lastModifiedDateTime" xmlns=""/>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="emailNav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="unbounded" name="PerEmail">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="false" maxOccurs="1" name="emailAddress">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="100"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="emailTypeNav">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element minOccurs="0" maxOccurs="1" name="PicklistOption">
                                                                                            <xs:complexType>
                                                                                                <xs:sequence>
                                                                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="externalCode">
                                                                                                        <xs:simpleType>
                                                                                                            <xs:restriction base="xs:string" xmlns="">
                                                                                                                <xs:maxLength value="256"/>
                                                                                                            </xs:restriction>
                                                                                                        </xs:simpleType>
                                                                                                    </xs:element>
                                                                                                </xs:sequence>
                                                                                            </xs:complexType>
                                                                                        </xs:element>
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                            <xs:element type="xs:dateTime" nillable="true" minOccurs="0" maxOccurs="1" name="lastModifiedDateTime" xmlns=""/>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element type="xs:dateTime" nillable="true" minOccurs="0" maxOccurs="1" name="lastModifiedDateTime" xmlns=""/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="jobInfoNav">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element minOccurs="0" maxOccurs="unbounded" name="EmpJob">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="costCenterNav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="1" name="FOCostCenter">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="description">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="128"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="description_defaultValue">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="128"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="false" maxOccurs="1" name="externalCode">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="14"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element type="xs:dateTime" nillable="false" maxOccurs="1" name="startDate" xmlns=""/>
                                                                            <xs:element type="xs:dateTime" nillable="true" minOccurs="0" maxOccurs="1" name="lastModifiedDateTime" xmlns=""/>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="positionNav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="1" name="Position">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="positionTitle">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="255"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element type="xs:dateTime" nillable="true" minOccurs="0" maxOccurs="1" name="lastModifiedDateTime" xmlns=""/>
                                                                            <xs:element type="xs:dateTime" nillable="false" maxOccurs="1" name="effectiveStartDate" xmlns=""/>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element type="xs:boolean" nillable="false" maxOccurs="1" name="isFulltimeEmployee" xmlns=""/>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="departmentNav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="1" name="FODepartment">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="false" maxOccurs="1" name="externalCode">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="32"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element type="xs:dateTime" nillable="false" maxOccurs="1" name="startDate" xmlns=""/>
                                                                            <xs:element type="xs:dateTime" nillable="true" minOccurs="0" maxOccurs="1" name="lastModifiedDateTime" xmlns=""/>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="employeeClassNav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="1" name="PicklistOption">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="externalCode">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="256"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="emplStatusNav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="1" name="PicklistOption">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="externalCode">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="256"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element type="xs:dateTime" nillable="true" minOccurs="0" maxOccurs="1" name="contractEndDate" xmlns=""/>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="eventNav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="1" name="PicklistOption">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="externalCode">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="256"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="eventReasonNav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="1" name="FOEventReason">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="false" maxOccurs="1" name="externalCode">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="32"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element type="xs:dateTime" nillable="false" maxOccurs="1" name="startDate" xmlns=""/>
                                                                            <xs:element type="xs:dateTime" nillable="true" minOccurs="0" maxOccurs="1" name="lastModifiedDateTime" xmlns=""/>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="event">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string" xmlns="">
                                                                <xs:maxLength value="32"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element nillable="false" maxOccurs="1" name="eventReason">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string" xmlns="">
                                                                <xs:maxLength value="256"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element type="xs:dateTime" nillable="false" maxOccurs="1" name="startDate" xmlns=""/>
                                                    <xs:element type="xs:dateTime" nillable="true" minOccurs="0" maxOccurs="1" name="lastModifiedDateTime" xmlns=""/>
                                                    <xs:element type="xs:string" nillable="true" minOccurs="0" maxOccurs="1" name="countryOfCompany" xmlns=""/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:dateTime" nillable="true" minOccurs="0" maxOccurs="1" name="serviceDate" xmlns=""/>
                            <xs:element type="xs:dateTime" nillable="false" maxOccurs="1" name="startDate" xmlns=""/>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="empJobRelationshipNav">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element minOccurs="0" maxOccurs="unbounded" name="EmpJobRelationships">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="relationshipTypeNav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="1" name="PicklistOption">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="externalCode">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="256"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element nillable="false" maxOccurs="1" name="relUserId">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string" xmlns="">
                                                                <xs:maxLength value="384"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element type="xs:dateTime" nillable="false" maxOccurs="1" name="startDate" xmlns=""/>
                                                    <xs:element type="xs:dateTime" nillable="true" minOccurs="0" maxOccurs="1" name="lastModifiedDateTime" xmlns=""/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="paymentInformationNav">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element minOccurs="0" maxOccurs="unbounded" name="PaymentInformationV3">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="toPaymentInformationDetailV3">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="unbounded" name="PaymentInformationDetailV3">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="routingNumber">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="255"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="accountNumber">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="255"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="accountOwner">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="40"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="bankNav">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element minOccurs="0" maxOccurs="1" name="Bank">
                                                                                            <xs:complexType>
                                                                                                <xs:sequence>
                                                                                                    <xs:element nillable="false" maxOccurs="1" name="bankName">
                                                                                                        <xs:simpleType>
                                                                                                            <xs:restriction base="xs:string" xmlns="">
                                                                                                                <xs:maxLength value="128"/>
                                                                                                            </xs:restriction>
                                                                                                        </xs:simpleType>
                                                                                                    </xs:element>
                                                                                                    <xs:element type="xs:dateTime" nillable="true" minOccurs="0" maxOccurs="1" name="lastModifiedDateTime" xmlns=""/>
                                                                                                </xs:sequence>
                                                                                            </xs:complexType>
                                                                                        </xs:element>
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="iban">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="35"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element type="xs:dateTime" nillable="true" minOccurs="0" maxOccurs="1" name="lastModifiedDateTime" xmlns=""/>
                                                                            <xs:element type="xs:dateTime" nillable="false" maxOccurs="1" name="PaymentInformationV3_effectiveStartDate" xmlns=""/>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element type="xs:dateTime" nillable="true" minOccurs="0" maxOccurs="1" name="lastModifiedDateTime" xmlns=""/>
                                                    <xs:element type="xs:dateTime" nillable="false" maxOccurs="1" name="effectiveStartDate" xmlns=""/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="compInfoNav">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element minOccurs="0" maxOccurs="unbounded" name="EmpCompensation">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="empPayCompRecurringNav">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="0" maxOccurs="unbounded" name="EmpPayCompRecurring">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element type="xs:double" nillable="false" maxOccurs="1" name="paycompvalue" xmlns=""/>
                                                                            <xs:element nillable="false" maxOccurs="1" name="currencyCode">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="32"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element nillable="false" maxOccurs="1" name="frequency">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string" xmlns="">
                                                                                        <xs:maxLength value="30"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:element>
                                                                            <xs:element type="xs:dateTime" nillable="false" maxOccurs="1" name="startDate" xmlns=""/>
                                                                            <xs:element type="xs:dateTime" nillable="true" minOccurs="0" maxOccurs="1" name="lastModifiedDateTime" xmlns=""/>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element type="xs:dateTime" nillable="true" minOccurs="0" maxOccurs="1" name="lastModifiedDateTime" xmlns=""/>
                                                    <xs:element type="xs:dateTime" nillable="false" maxOccurs="1" name="startDate" xmlns=""/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:dateTime" nillable="false" maxOccurs="1" name="benefitsEligibilityStartDate" xmlns=""/>
                            <xs:element type="xs:dateTime" nillable="true" minOccurs="0" maxOccurs="1" name="lastModifiedDateTime" xmlns=""/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
