<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="RootNode">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="RowNode" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="PERSON_ID" type="xs:string" />
							<!--<xs:element name="JOB_LEVEL_COMMON_CODE" type="xs:string" />
							<xs:element name="JOB_LEVEL_COMMON_TEXT" type="xs:string" />-->
							<xs:element name="TIME_IN_LEVEL_COMMON" type="xs:string" />
							<!--<xs:element name="PBUSMAIL" type="xs:string" />-->
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>