<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="cust_Independence_Ruleset_Scope">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" name="cust_Independence_Ruleset_Scope">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element nillable="false" maxOccurs="1" name="cust_Priority">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="255"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="cust_RULESET">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="255"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="cust_SCOPE">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="255"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                             <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="RULESETDetermination">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="255"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                             <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="SCOPEDetermination">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="255"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                               <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="cust_RULE_NOTE">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="255"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                               <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="cust_SCOPE_NOTE">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="255"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="Message">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="255"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
