<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="cust_IndependenceProfile">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" name="cust_IndependenceProfile">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:dateTime" nillable="false" maxOccurs="1" name="effectiveStartDate" xmlns=""/>
                            <xs:element nillable="false" maxOccurs="1" name="externalCode">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="createdBy">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element type="xs:dateTime" nillable="true" minOccurs="0" maxOccurs="1" name="createdDateTime" xmlns=""/>
                            <xs:element nillable="false" maxOccurs="1" name="cust_RuleSet">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="cust_RuleSetComments">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="255"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="cust_RuleSetOvrRide1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element nillable="false" maxOccurs="1" name="cust_Scope">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="cust_ScopeComments">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="255"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="cust_ScopeOvrRide1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="cust_ScopeOvrRide2">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="cust_ScopeOvrRide3">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="cust_ScopeOvrRide4">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="cust_ScopeOvrRide5">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="externalName">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="128"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="lastModifiedBy">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element type="xs:dateTime" nillable="true" minOccurs="0" maxOccurs="1" name="lastModifiedDateTime" xmlns=""/>
                            <xs:element type="xs:dateTime" nillable="true" minOccurs="0" maxOccurs="1" name="mdfSystemEffectiveEndDate" xmlns=""/>
                            <xs:element nillable="true" minOccurs="0" maxOccurs="1" name="mdfSystemRecordStatus">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="255"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
