<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="cust_IndependenceProfile">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="cust_IndependenceProfile" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
		                    <xs:element name="externalCode"  minOccurs="0"/>
	                        <xs:element name="effectiveStartDate"  minOccurs="0"/>
	                        <xs:element name="mdfSystemEffectiveEndDate"  minOccurs="0"/>
	                    </xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>