<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Record" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:int" name="Personnelnumber"/>
              <xs:element type="xs:string" name="Begindate"/>
              <xs:element type="xs:string" name="Enddate"/>
              <xs:element type="xs:string" name="Costcentercode"/>
              <xs:element type="xs:string" name="Costcentertext"/>
              <xs:element type="xs:string" name="Oldscopevalue"/>
              <xs:element type="xs:string" name="Newscopevalue"/>
              <xs:element type="xs:string" name="Oldrulevalue"/>
              <xs:element type="xs:string" name="Newrulevalue"/>
              <xs:element type="xs:string" name="Message"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>