<!-- Code Generated by Sidekick is for learning and experimentation purposes only. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                version="3.0">

  <xsl:output method="xml" indent="yes"/>

  <!-- Match the root EmpEmployment element -->
  <xsl:template match="/EmpEmployment">
    <EmpEmployment>
      <xsl:for-each select="EmpEmployment/personNav/PerPerson/personRerlationshipNav/PerPersonRelationship">
        <EmpEmployment>
          <!-- Copy everything from the original EmpEmployment except personNav -->
          <xsl:copy-of select="../../../../*[not(self::personNav)]"/>
          <!-- Rebuild personNav with only the current relationship -->
          <personNav>
            <PerPerson>
              <personRerlationshipNav>
                <xsl:copy-of select="."/>
              </personRerlationshipNav>
              <!-- Copy the rest of PerPerson except personRerlationshipNav -->
              <xsl:copy-of select="../../*[not(self::personRerlationshipNav)]"/>
            </PerPerson>
          </personNav>
        </EmpEmployment>
      </xsl:for-each>
    </EmpEmployment>
  </xsl:template>
</xsl:stylesheet>