import com.sap.it.api.mapping.*;

/*Add MappingContext parameter to read or set headers and properties
def String customFunc1(String P1,String P2,MappingContext context) {
         String value1 = context.getHeader(P1);
         String value2 = context.getProperty(P2);
         return value1+value2;
}

Add Output parameter to assign the output value.
def void custFunc2(String[] is,String[] ps, Output output, MappingContext context) {
        String value1 = context.getHeader(is[0]);
        String value2 = context.getProperty(ps[0]);
        output.addValue(value1);
        output.addValue(value2);
}*/

def String ReplaceSpace(String input){
        def Value = input.replace(" ", ",")
	    return Value
}


// Code Generated by Sidekick is for learning and experimentation purposes only.
def String formatName(String input) {
    if (input == null) return null
    def s = input.trim()
    if (!s) return s                     // empty or whitespace input
    if (s.contains(',')) return s        // already formatted with a comma
    List<String> parts = s.split(/\s+/) as List
    if (parts.size() == 1) return s      // single token → nothing to format
    // Add a comma after every token except the last
    def left = parts.size() > 1 ? parts[0..-2].collect { it + ',' } : []
    return (left + parts[-1]).join(' ')
}